import { NextResponse } from "next/server";

import {
  DEMO_TRANSCRIPT,
  getDemoActionItemsUpTo,
  getDemoCaptionsUpTo,
} from "@/lib/demo";
import { buildMissedSegmentPrompt } from "@/lib/llm";
import type { MissedSegmentRequest } from "@/types";

export async function POST(request: Request) {
  const body = (await request.json()) as MissedSegmentRequest;

  if (
    typeof body.fromTimestamp !== "number" ||
    typeof body.toTimestamp !== "number"
  ) {
    return NextResponse.json(
      { error: "fromTimestamp and toTimestamp are required" },
      { status: 400 },
    );
  }

  const captions = getDemoCaptionsUpTo(body.toTimestamp).filter(
    (chunk) =>
      chunk.timestamp >= body.fromTimestamp &&
      chunk.timestamp <= body.toTimestamp,
  );

  const transcript = captions.map((c) => `${c.speaker}: ${c.text}`).join("\n");
  void buildMissedSegmentPrompt(transcript);

  const isDemoGap =
    body.fromTimestamp >= 80 && body.toTimestamp <= 170 && captions.length > 0;

  if (isDemoGap || process.env.NEXT_PUBLIC_DEMO_MODE === "true") {
    return NextResponse.json({
      recap:
        "While you were away: The team decided to keep the old dashboard for version 1. Sarah will refactor the sign-in code and needs Marcus to document the auth flow by Wednesday. Jordan will update design files to match the v1 dashboard.",
      actionItems: getDemoActionItemsUpTo(body.toTimestamp).filter(
        (item) =>
          item.timestamp >= body.fromTimestamp &&
          item.timestamp <= body.toTimestamp,
      ),
    });
  }

  return NextResponse.json({
    recap: captions.length
      ? `Recap for ${body.fromTimestamp}s–${body.toTimestamp}s will be generated by the LLM in Phase 2.`
      : "No transcript found for that time range.",
    actionItems: [],
    stub: true,
    demoAvailable: DEMO_TRANSCRIPT.chunks.length > 0,
  });
}
